apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 3
  selector: 
    matchLabels: 
      component: worker
  template:
    metadata:
      labels: 
        component: worker
    spec: 
      containers:
        - name: servworkerer
          image: stephengrider/multi-worker
          ports:
            - containerPort: 6000
